"""add_animate_generation_type_and_fields

Revision ID: 2e08cf44b640
Revises: 922a42abde2d
Create Date: 2025-12-31 19:19:28.751894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e08cf44b640'
down_revision: Union[str, Sequence[str], None] = '922a42abde2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check existing columns (for databases created before alembic)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = set(c['name'] for c in inspector.get_columns('generations'))

    # All columns that should exist (from baseline + this migration)
    columns_to_add = [
        # From baseline (may be missing in pre-alembic databases)
        ('generation_type', sa.String(length=20)),
        ('source_generation_id', sa.String(length=36)),
        ('mask_path', sa.String(length=500)),
        ('denoising_strength', sa.Float()),
        ('grow_mask_by', sa.Integer()),
        ('upscale_factor', sa.Float()),
        ('upscale_model', sa.String(length=100)),
        ('sharpen_amount', sa.Float()),
        ('outpaint_left', sa.Integer()),
        ('outpaint_right', sa.Integer()),
        ('outpaint_top', sa.Integer()),
        ('outpaint_bottom', sa.Integer()),
        ('outpaint_feather', sa.Integer()),
        # From this migration (animation fields)
        ('video_path', sa.String(length=500)),
        ('motion_bucket_id', sa.Integer()),
        ('fps', sa.Integer()),
        ('duration_seconds', sa.Float()),
    ]

    for col_name, col_type in columns_to_add:
        if col_name not in columns:
            op.add_column('generations', sa.Column(col_name, col_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'duration_seconds')
    op.drop_column('generations', 'fps')
    op.drop_column('generations', 'motion_bucket_id')
    op.drop_column('generations', 'video_path')
    # ### end Alembic commands ###
