"""add_animate_generation_type_and_fields

Revision ID: 2e08cf44b640
Revises: 922a42abde2d
Create Date: 2025-12-31 19:19:28.751894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e08cf44b640'
down_revision: Union[str, Sequence[str], None] = '922a42abde2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('video_path', sa.String(length=500), nullable=True))
    op.add_column('generations', sa.Column('motion_bucket_id', sa.Integer(), nullable=True))
    op.add_column('generations', sa.Column('fps', sa.Integer(), nullable=True))
    op.add_column('generations', sa.Column('duration_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'duration_seconds')
    op.drop_column('generations', 'fps')
    op.drop_column('generations', 'motion_bucket_id')
    op.drop_column('generations', 'video_path')
    # ### end Alembic commands ###
