"""baseline

Revision ID: 922a42abde2d
Revises:
Create Date: 2025-12-31 19:12:31.357462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922a42abde2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_json', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('generation_type', sa.String(length=20), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('cfg_scale', sa.Float(), nullable=True),
    sa.Column('sampler', sa.String(length=50), nullable=True),
    sa.Column(
        'status',
        sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatus'),
        nullable=True
    ),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('source_generation_id', sa.String(length=36), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('model_filename', sa.String(length=500), nullable=True),
    sa.Column('lora_filename', sa.String(length=500), nullable=True),
    sa.Column('mask_path', sa.String(length=500), nullable=True),
    sa.Column('denoising_strength', sa.Float(), nullable=True),
    sa.Column('grow_mask_by', sa.Integer(), nullable=True),
    sa.Column('upscale_factor', sa.Float(), nullable=True),
    sa.Column('upscale_model', sa.String(length=100), nullable=True),
    sa.Column('sharpen_amount', sa.Float(), nullable=True),
    sa.Column('outpaint_left', sa.Integer(), nullable=True),
    sa.Column('outpaint_right', sa.Integer(), nullable=True),
    sa.Column('outpaint_top', sa.Integer(), nullable=True),
    sa.Column('outpaint_bottom', sa.Integer(), nullable=True),
    sa.Column('outpaint_feather', sa.Integer(), nullable=True),
    sa.Column('comfyui_prompt_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['generations.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['source_generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generations')
    op.drop_table('workflow_templates')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
